analyzer:
  project_name: HealthPlus

  # Essential
  project_root: /Users/kaima/src/HealthPlus/src/main/java
  schema_files:
    - /Users/kaima/src/HealthPlus/database/hms_db.sql

  additional_class_paths:
    - /Users/kaima/src/HealthPlus/target/dependency/
    - /Users/kaima/src/HealthPlus/target/classes/

  additional_basic_effects:
    - com.hms.hms_test_2.DatabaseOperator.addTableRow
    - com.hms.hms_test_2.DatabaseOperator.deleteTableRow
    - com.hms.hms_test_2.DatabaseOperator.customDeletion
    - com.hms.hms_test_2.DatabaseOperator.customInsertion

  additional_basic_updates:
    - com.hms.hms_test_2.DatabaseOperator.customInsertion
    - com.hms.hms_test_2.DatabaseOperator.customSelection

  exclude_pattern:
    - ^com.hms.hms_test_2.DatabaseOperator
    - ^com.hms.hms_test_2.User
    - Controller$
    - ^com.hms.hms_test_2.Validate
    - ^com.hms.hms_test_2.AllMessages
    - ^Receptionist.DoctorDetail
    # The following are too slow...
    # - Receptionist.Receptionist.makeAppointment

  additional_semantics:
    - HealthPlus

  debug:
    build_intergraph: false
    only_effects:
      - Doctor.Doctor.updateProfileInfo(java.lang.String)

  # Enable optimizations to improve commutativity?
  opt: false

  graphviz:
    intergraph:
      output: false
      onlyEffect: true
    intragraph:
      output: false

rigi:
  generate: true
  output_file: /tmp/output.py
