analyzer:
  project_name: HealthPlus

  # Basic information.
  project_root: /Users/kaima/src/HealthPlus/src/main/java
  schema_files:
    - /Users/kaima/src/HealthPlus/database/hms_db.sql

  # Additional class paths for resolving symbols and types.
  # If a path ends with /, all jar files under it, and the directory itself, are added.
  additional_class_paths:
    - /Users/kaima/src/HealthPlus/target/dependency/
    - /Users/kaima/src/HealthPlus/target/classes/

  # Used by interprocedural analysis for determining the effectual methods.
  additional_basic_effects:
    - com.hms.hms_test_2.DatabaseOperator.addTableRow
    - com.hms.hms_test_2.DatabaseOperator.deleteTableRow
    - com.hms.hms_test_2.DatabaseOperator.customDeletion
    - com.hms.hms_test_2.DatabaseOperator.customInsertion

  # Used by intraprocedural analysis to find effectual paths.
  additional_basic_updates:
    - com.hms.hms_test_2.DatabaseOperator.customInsertion
    - com.hms.hms_test_2.DatabaseOperator.customDeletion
    - com.hms.hms_test_2.DatabaseOperator.addTableRow
    - com.hms.hms_test_2.DatabaseOperator.deleteTableRow

  # If a qualified name (a class or a method) can be matched by one of the patterns, it's excluded from analysis.
  exclude_pattern:
    - ^com.hms.hms_test_2.DatabaseOperator
    - ^com.hms.hms_test_2.User
    - Controller$
    - ^com.hms.hms_test_2.Validate
    - ^com.hms.hms_test_2.AllMessages
    - ^Receptionist.DoctorDetail

  additional_semantics:
    - HealthPlus

  interesting_exceptions:
    - SQLException

  patches:
    arg_types:
      "LabAssistant.LabAssistant.UrineFullReport":
        ph: float
      "LabAssistant.LabAssistant.completeBloodCount":
        haemoglobin: float
        redBloodCells: float
        meanCellVolume: float
        haematocrit: float
        meanCellHaemoglobin: float
        mchConcentration: float
        redCellsDistributionWidth: float
      "LabAssistant.LabAssistant.RenalFunctionTest":
        creatinine: float
        urea: float
        totalBilirubin: float
        directBilirubin: float
        sgotast: float
        sgptalt: float
        alkalinePhospates: float
      "LabAssistant.LabAssistant.liverFunctionTest":
        totalProtein: float
        albumin: float
        globulin: float
        totalBilirubin: float
        directBilirubin: float
        sgotast: float
        sgptalt: float
        alkalinePhospates: float

  debug:
    build_intergraph: true
    only_effects: []

  # Enable optimizations to improve commutativity?
  opt: false

  graphviz:
    intergraph:
      output: false
      onlyEffect: true
    intragraph:
      output: false

rigi:
  generate: true
  output_file: /tmp/output.py
