analyzer:
  # Essential
  project_root: /Users/kaima/src/HealthPlus/src/main/java
  schema_files:
    - /Users/kaima/src/HealthPlus/database/hms_db.sql

  # TODO: this doesn't work yet
  additional_class_paths:
    - /Users/kaima/src/HealthPlus/target/classes

  additional_basic_effects:
    - com.hms.hms_test_2.DatabaseOperator.addTableRow
    - com.hms.hms_test_2.DatabaseOperator.deleteTableRow
    - com.hms.hms_test_2.DatabaseOperator.customDeletion
    - com.hms.hms_test_2.DatabaseOperator.customInsertion

  # Enable optimizations to improve commutativity?
  opt: false

  exclude_classes:
    - com.hms.hms_test_2.DatabaseOperator
    - com.hms.hms_test_2.User

  graphviz:
    intergraph:
      output: true
      onlyEffect: true
    intragraph:
      output: false

rigi:
  generate: false
  output_file: /tmp/output.py
