analyzer:
  # Essential
  project_root: /Users/kaima/src/HealthPlus/src/main/java
  schema_files:
    - /Users/kaima/src/HealthPlus/database/hms_db.sql

  # TODO: this doesn't work yet
  additional_class_paths:
    - /Users/kaima/src/HealthPlus/target/classes

  additional_basic_effects:
    - com.hms.hms_test_2.DatabaseOperator.addTableRow
    - com.hms.hms_test_2.DatabaseOperator.deleteTableRow
    - com.hms.hms_test_2.DatabaseOperator.customDeletion
    - com.hms.hms_test_2.DatabaseOperator.customInsertion

  additional_basic_updates:
    - com.hms.hms_test_2.DatabaseOperator.customInsertion
    - com.hms.hms_test_2.DatabaseOperator.customSelection

  exclude:
    - com.hms.hms_test_2.DatabaseOperator.createDatabase
    - com.hms.hms_test_2.DatabaseOperator.showDatabases
    - com.hms.hms_test_2.DatabaseOperator.useDatabase
    - com.hms.hms_test_2.DatabaseOperator.createTable
    - com.hms.hms_test_2.DatabaseOperator.showTables
    - com.hms.hms_test_2.DatabaseOperator.deleteDatabase
    - com.hms.hms_test_2.DatabaseOperator.deleteTable
    - com.hms.hms_test_2.DatabaseOperator.addTableRow
    - com.hms.hms_test_2.DatabaseOperator.deleteTableRow
    - com.hms.hms_test_2.DatabaseOperator.customInsertion
    - com.hms.hms_test_2.DatabaseOperator.customDeletion

  additional_semantics:
    - HealthPlus

  debug:
    build_intergraph: false
    only_effects:
#      - Doctor.Doctor.updateAccountInfo(java.lang.String)
#      - Doctor.Doctor.updateProfileInfo(java.lang.String)
#      - Doctor.Doctor.updateDoctorInfo(java.lang.String)
#      - Pharmacist.Pharmacist.updateProfileInfo(java.lang.String)
#      - Pharmacist.Pharmacist.updatePharmacistInfo(java.lang.String)
#      - Pharmacist.Pharmacist.updateAccountInfo(java.lang.String)
#      - Admin.Admin.suspendUser(java.lang.String)
#      - Admin.Admin.unsuspendUser(java.lang.String)
      - LabAssistant.LabAssistant.updateProfileInfo(java.lang.String)
      - LabAssistant.LabAssistant.updateLabAssistantInfo(java.lang.String)
      - LabAssistant.LabAssistant.updateAccountInfo(java.lang.String)
      - LabAssistant.LabAssistant.UrineFullReport(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
      - LabAssistant.LabAssistant.LipidTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
      - LabAssistant.LabAssistant.BloodGroupingTest(java.lang.String, java.lang.String, java.lang.String)
      - LabAssistant.LabAssistant.completeBloodCount(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
      - LabAssistant.LabAssistant.RenalFunctionTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
      - LabAssistant.LabAssistant.SeriumCreatinePhosphokinaseTotal(java.lang.String, java.lang.String)
      - LabAssistant.LabAssistant.SeriumCreatinePhosphokinase(java.lang.String, java.lang.String)
      - LabAssistant.LabAssistant.liverFunctionTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)

  # Enable optimizations to improve commutativity?
  opt: false

  exclude_classes:
    - com.hms.hms_test_2.DatabaseOperator
    - com.hms.hms_test_2.User

  graphviz:
    intergraph:
      output: false
      onlyEffect: true
    intragraph:
      output: false

rigi:
  generate: false
  output_file: /tmp/output.py
